const prompt = require("prompt-sync")();

let x = Number(prompt("Enter a number: "));
console.log("The number you entered is:", x);
const y = Number(prompt("Enter another number: "));
console.log("The second number you entered is:", y);
 x += y;
console.log("The sum of the two numbers is:", x);
x -= y;
console.log("After subtracting the second number, the result is:", x);
x *= y;
console.log("After multiplying by the second number, the result is:", x);
x /= y;
console.log("After dividing by the second number, the result is:", x);
x %= y;
console.log("After taking the modulus with the second number, the result is:", x);
x++;
console.log("After incrementing by 1, the result is:", x);
x--;
console.log("After decrementing by 1, the result is:", x);
x **= y;
console.log("After raising to the power of the second number, the result is:", x);
x &= y;
console.log("After performing bitwise AND with the second number, the result is:", x);
x |= y;
console.log("After performing bitwise OR with the second number, the result is:", x);
x ^= y;
console.log("After performing bitwise XOR with the second number, the result is:", x);
x <<= y;
console.log("After performing left shift by the second number, the result is:", x);
x >>= y;
console.log("After performing right shift by the second number, the result is:", x);
x >>>= y;
console.log("After performing unsigned right shift by the second number, the result is:", x);